### ISSUE TITLE
Problems arise when using Shared modules

### ISSUE THREAD

**Issue by yanandgit** [ninia/jep#104]
- OS Platform, Distribution, and Version:  Wondows 10 x64
- Python Distribution and Version: python-2.7.14.amd64
- Java Distribution and Version: jdk1.8.0_144

The following code works:
```Java
    @Test
    public void test7() throws Exception {
        try(Jep jep = new Jep()) {
            jep.eval("print('222222222222222222')");
        }
    }
```
When I used the contribution module, I encountered the following problems:
```Java
    @Test
    public void test6() throws Exception {
        try(Jep jep = new Jep(new JepConfig().addSharedModules("numpy"))) {
            float[] f = new float[] { 1.0f, 2.1f, 3.3f, 4.5f, 5.6f, 6.7f };
            NDArray<float[]> nd = new NDArray<>(f, 3, 2);
            jep.set("x", nd);
        }
    }
```
```
jep.JepException: <type 'exceptions.ImportError'>: No module named _jep
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:609)
	at jep.Jep.<init>(Jep.java:427)
```
Thank you very much!

**Comment by ndjensen** [comment]
I'm perplexed by your issue.  Do you get a printout "WARNING: couldn't import module _jep."?  https://github.com/ninia/jep/blob/dev_3.7/src/jep/pyembed.c#L161

**Comment by ndjensen** [comment]
Closing due to a lack of activity.  Please reopen if you have more information to add to the ticket.

**Comment by bouisa** [comment]
I have the same issue as @yanandgit where his first test case works fine, but calling JepConfig.addSharedModules() with any value causes the error.

- jep: 3.7.1
- Windows 10 x64
- Python 2.7.13 :: Anaconda 4.3.0 (64-bit)
- JDK: 1.8.0_171

To answer your question above, I do get the printout ""WARNING: couldn't import module _jep.":
```
@Test
public void test3() throws JepException {
    try (Jep jep = new Jep(new JepConfig().addSharedModules("anything"))) {
        jep.eval("print('bla')"); // doesn't get here
    }
}
```
```
<type 'exceptions.ImportError'>: No module named _jep
jep.JepException: <type 'exceptions.ImportError'>: No module named _jep
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:609)
	at jep.Jep.<init>(Jep.java:427)

WARNING: couldn't import module _jep.
```

**Comment by ndjensen** [comment]
If you run `python setup.py test` do the tests pass?  Also it looks like you're using JUnit.  Can you provide more of your JUnit test code so we can see what happens in tests that run earlier and if there's any `setUp()` or `tearDown()` methods?

**Comment by bouisa** [comment]
The tests appear to pass (though it says skipped=26):
```
>python setup.py test
numpy include found at C:\Anaconda2\lib\site-packages\numpy\core\include
running test
running build
running setup_java
running build_java
running build_javah
running build_jar
running build_py
running build_ext
running build_scripts
............................................s........sss.......s...............................................s.........sssssssssssss....ssssss..s..............................................
----------------------------------------------------------------------
Ran 193 tests in 1.224s

OK (skipped=26)
```

My JUnit test code is completely stripped down for this specific issue with no setup/tear down: 
```
public class TestJepTest {

    @Test
    public void test1() throws Exception {
        try (Jep jep = new Jep()) {
            jep.eval("import sys");
            jep.eval("print(sys)");
            jep.eval("msg = 'hello jep!'");
            assertEquals("hello jep!", (String) jep.getValue("msg"));
        }
    }

    @Test
    public void test2() throws Exception {
        try (Jep jep = new Jep(new JepConfig().addSharedModules("sys"))) {
            jep.eval("msg = 'hello jep!'");
            assertEquals("hello jep!", (String) jep.getValue("msg"));
        }
    }

    @Test
    public void test3() throws Exception {
        try (Jep jep = new Jep(new JepConfig().addSharedModules("anything"))) {
            jep.eval("msg = 'hello jep!'");
            assertEquals("hello jep!", (String) jep.getValue("msg"));
        }
    }

}
```
`test1` passes, `test2` and `test3 `throw the same error:
```
Testcase: test2(testjep.TestJepTest):	Caused an ERROR
<type 'exceptions.ImportError'>: No module named _jep
jep.JepException: <type 'exceptions.ImportError'>: No module named _jep
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:609)
	at jep.Jep.<init>(Jep.java:427)
	at testjep.TestJepTest.test2(TestJepTest.java:25)


Testcase: test3(testjep.TestJepTest):	Caused an ERROR
<type 'exceptions.ImportError'>: No module named _jep
jep.JepException: <type 'exceptions.ImportError'>: No module named _jep
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:609)
	at jep.Jep.<init>(Jep.java:427)
	at testjep.TestJepTest.test3(TestJepTest.java:33)


WARNING: couldn't import module _jep.
WARNING: couldn't import module _jep.
Test testjep.TestJepTest FAILED
```
Outside of the JUnit context I can create a simple java program that encounters the same error:
```
public class TestJep {
    public static void main(String[] args) throws JepException {
        try (Jep jep = new Jep(new JepConfig().addSharedModules("sys"))) {
            jep.eval("bla"); // doesn't get here
        }
    }
}
```
```
Exception in thread "main" jep.JepException: <type 'exceptions.ImportError'>: No module named _jep
WARNING: couldn't import module _jep.
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:609)
	at jep.Jep.<init>(Jep.java:427)
	at testjep.TestJep.main(TestJep.java:23)
```
I have tried with Anaconda and, afterwards, the official distribution: 
- Python 2.7.13 :: Anaconda 4.3.0 (64-bit)
- Python 2.7.15 (64-bit)
Both have the identical issue.

**Comment by bouisa** [comment]
I actually want to share a C extension module, win32com.client, because I'm having issues importing it in separate jep instances (whereas it works fine within a single jep instance).  I assume the error occurs before actually resolving any specified shared module because the same error happens on the first `new Jep(cfg)` call regardless of what module I pass into` JepConfig.addSharedModules()` e.g.:

```
public static void main(String[] args) throws JepException {
    JepConfig cfg = new JepConfig().addSharedModules("win32com.client");
    Jep jep = new Jep(cfg); // error here
}
```
```
public static void main(String[] args) throws JepException {
    JepConfig cfg = new JepConfig().addSharedModules("numpy");
    Jep jep = new Jep(cfg); // error here
}
```

**Comment by ndjensen** [comment]
Do you have multiple Pythons installed on your system?  What are your PATH and PYTHONHOME environment variables set to?

**Comment by ndjensen** [comment]
I improved the error logging on the dev_3.8 branch if you want to try that.  It should print out more information about what is going wrong.

**Comment by mjames-upc** [comment]
I'm also encountering this error on Windows 10 with Miniconda Python 2.7, Java 1.8, Eclipse 4.6.1

After reinstalling from the dev_3.8 branch like you said on Jun 21, I see the error messages below.

```
com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:94)
	at com.raytheon.viz.pointdata.util.PointDataCubeAdapter.getPoints(PointDataCubeAdapter.java:153)
	at com.raytheon.viz.pointdata.util.PointDataCubeAdapter.getPoints(PointDataCubeAdapter.java:103)
	at com.raytheon.uf.viz.datacube.DataCubeContainer.getPointData(DataCubeContainer.java:168)
	at com.raytheon.uf.viz.datacube.DataCubeContainer.getPointData(DataCubeContainer.java:176)
	at com.raytheon.viz.pointdata.thread.PlotModelDataRequestJob.requestData(PlotModelDataRequestJob.java:257)
	at com.raytheon.viz.pointdata.thread.PlotModelDataRequestJob.run(PlotModelDataRequestJob.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.ExecutionException: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Couldn't add module _jep
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.get(PythonInterpreterThreadPoolExecutor.java:208)
	at com.raytheon.uf.common.derivparam.python.DerivParamPythonFunctionAdapter.executeFunction(DerivParamPythonFunctionAdapter.java:151)
	at com.raytheon.uf.common.derivparam.library.DerivedParameterGenerator.calculate(DerivedParameterGenerator.java:205)
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:86)
	... 7 common frames omitted
Caused by: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Couldn't add module _jep
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:235)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.run(PythonInterpreterThreadPoolExecutor.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$PythonThread.run(PythonThreadFactory.java:121)
Caused by: java.lang.IllegalStateException: Couldn't add module _jep
	at jep.Jep.init(Native Method)
	at jep.Jep.<init>(Jep.java:252)
	at jep.Jep.<init>(Jep.java:228)
	at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:133)
	at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:102)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.<init>(MasterDerivScript.java:98)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptFactory.createPythonScript(MasterDerivScriptFactory.java:87)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptFactory.createPythonScript(MasterDerivScriptFactory.java:1)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:79)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:1)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:232)
	... 6 common frames omitted


```

---


* I removed the jep.pyd file in Miniconda2\Lib\site-packages\jep as mentioned at https://github.com/ninia/jep/wiki/Windows#other-insights
* -Djava.library.path="C:\Users\mjames\Miniconda2\Lib\site-packages"
* Running Scripts\jep.bat shows the following:
```
(base) C:\Users\mjames\Miniconda2\Scripts>jep.bat

(base) C:\Users\mjames\Miniconda2\Scripts>SETLOCAL

(base) C:\Users\mjames\Miniconda2\Scripts>SET VIRTUAL_ENV=

(base) C:\Users\mjames\Miniconda2\Scripts>IF NOT "" == "" (
SET PATH="\bin";"C:\Program Files\Java\jdk1.8.0_171\bin";"C:\Users\mjames\Miniconda2;C:\Users\mjames\Miniconda2\Library\mingw-w64\bin;C:\Users\mjames\Miniconda2\Library\usr\bin;C:\Users\mjames\Miniconda2\Library\bin;C:\Users\mjames\Miniconda2\Scripts;C:\Users\mjames\Miniconda2\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\VanDyke Software\Clients\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Java\jdk1.8.0_171\bin;C:\Program Files\Git\cmd;C:\Users\mjames\Miniconda2;C:\Users\mjames\Miniconda2\Library\mingw-w64\bin;C:\Users\mjames\Miniconda2\Library\usr\bin;C:\Users\mjames\Miniconda2\Library\bin;C:\Users\mjames\Miniconda2\Scripts;C:\Users\mjames\AppData\Local\Microsoft\WindowsApps;C:\Users\mjames\Miniconda2\Lib\site-packages\jep;C:\Users\mjames\Miniconda2\DLLs;"
 SET PYTHONHOME=
)

(base) C:\Users\mjames\Miniconda2\Scripts>SET cp="C:\Users\mjames\Miniconda2\Lib\site-packages\jep\jep-3.8.2.jar"

(base) C:\Users\mjames\Miniconda2\Scripts>IF DEFINED CLASSPATH (SET cp="C:\Users\mjames\Miniconda2\Lib\site-packages\jep\jep-3.8.2.jar"; )

(base) C:\Users\mjames\Miniconda2\Scripts>SET jni_path="C:\Users\mjames\Miniconda2\Lib\site-packages\jep"

(base) C:\Users\mjames\Miniconda2\Scripts>SET args=

(base) C:\Users\mjames\Miniconda2\Scripts>IF "" == "" (SET args="C:\Users\mjames\Miniconda2\Lib\site-packages\jep\console.py" )

(base) C:\Users\mjames\Miniconda2\Scripts>java -classpath "C:\Users\mjames\Miniconda2\Lib\site-packages\jep\jep-3.8.2.jar" -Djava.library.path="C:\Users\mjames\Miniconda2\Lib\site-packages\jep" jep.Run "C:\Users\mjames\Miniconda2\Lib\site-packages\jep\console.py"

              No readline available. History will not be available.

                   For Windows use pyreadline and get it from the official git
                   repo on github:
                   https://github.com/pyreadline/pyreadline

                   Do NOT use the version on pypi.python.org, and therefore
                   Do NOT use the version installed by pip.  It is out of date
                   and doesn't work with Jep!

>>>
```

**Comment by ndjensen** [comment]
The problem occurs at the startup of Jep so we can't safely get the underlying Python error message out of it and into a Java JepException.  Can you check your console or sysout to see if you got more of an error message out of it?  More output should go to the console/sysout that will potentially tell us the underlying problem.  https://github.com/ninia/jep/blob/v3.8.2/src/main/c/Jep/pyembed.c#L336

**Comment by mjames-upc** [comment]
On the console, along with the IllegalStateException thrown in the application, I see 

SystemError: ..\Objects\moduleobject.c:50: bad argument to internal function

**Comment by ndjensen** [comment]
Thanks.  I'm not sure what to make of that but that's the underlying problem.

Since jep.bat works, it is most likely something wrong with your variables, in particular the environment variable PATH.  Can you set and confirm at runtime in the application that the PATH environment variable is set to match the one in jep.bat?

**Comment by mjames-upc** [comment]
I got past the error by moving from Minoconda2 to Miniconda3 (Python 3.7.0) on Windows 10. No tricks or surprises, only had to edit some script files for Python 3 compliance.

However, both Miniconda2 and Windows Python 2.7.15 (from https://www.python.org/downloads/) produced the `moduleobject.c:50: bad argument to internal function` error message.

**Comment by ndjensen** [comment]
Not surprised it works with Python 3.  Python 3 handles some things better, and Jep has to have different code for Python 2 vs Python 3 in some places, this initialization being one of those places.
