### ISSUE TITLE
Jep sends java.lang.UnsupportedClassVersionError: jep/JepException : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by nando2301** [ninia/jep#106]
**OS Platform:** OS X 10.11.4 (El Capitan)

**Python Distribution and Version:** Python 2.7.11

**JDK:** javac 1.7.0_79 

**JRE:**

java version "1.7.0_79"

Java(TM) SE Runtime Environment (build 1.7.0_79-b15)

Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

**IDE:** Netbeans 8.2

**Server:** Glassfish 4.1

**Framework:** JSF 2.2

When I try to run following example, it returns an exception:

```
    public void runScript() throws JepException {
        try (Jep jep = new Jep(false)) {
            jep.eval("import somePyModule");
            // any of the following work, these are just pseudo-examples
            Object obj = null;

            // using eval(String) to invoke methods
            //jep.setValue("arg", obj);
            jep.eval("x = somePyModule.foo1(arg)");
            Object result1 = jep.getValue("x");

            // using getValue(String) to invoke methods
            Object result2 = jep.getValue("somePyModule.foo2()");

            // using invoke to invoke methods
            jep.eval("foo3 = somePyModule.foo3");
            Object result3 = jep.invoke("foo3", obj);

            // using runScript
            jep.runScript("/Users/fernando/Documents/ms/Proyectos/Aeromexico/python-scripts/pyexcel.py");
        } catch (JepException je) {
            message = new FacesMessage(je.getMessage());
            message.setSeverity(FacesMessage.SEVERITY_ERROR);
            throw new JepException(message.getDetail());
        }
    }
```

Exception:

```
Grave:   java.lang.UnsupportedClassVersionError: jep/JepException : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1730)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1633)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at com.sun.faces.util.Util.loadClass(Util.java:364)
	at com.sun.faces.mgbean.BeanBuilder.loadClass(BeanBuilder.java:255)
	at com.sun.faces.mgbean.BeanBuilder.loadBeanClass(BeanBuilder.java:400)
	at com.sun.faces.mgbean.BeanBuilder.bake(BeanBuilder.java:381)
	at com.sun.faces.mgbean.ManagedBeanBuilder.bake(ManagedBeanBuilder.java:90)
	at com.sun.faces.mgbean.BeanManager.preProcessBean(BeanManager.java:353)
	at com.sun.faces.mgbean.BeanManager.create(BeanManager.java:262)
	at com.sun.faces.el.ManagedBeanELResolver.resolveBean(ManagedBeanELResolver.java:257)
	at com.sun.faces.el.ManagedBeanELResolver.getValue(ManagedBeanELResolver.java:117)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
	at com.sun.el.parser.AstIdentifier.getValue(AstIdentifier.java:116)
	at com.sun.el.parser.AstValue.getBase(AstValue.java:151)
	at com.sun.el.parser.AstValue.getTarget(AstValue.java:170)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:272)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
	at javax.faces.component.UIData.broadcast(UIData.java:1108)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)


```
On `jep` page dependencies has >= JDK 1.7 [(Dependencies)](https://github.com/ninia/jep#dependencies) but `jep-3.7.1.jar` has JDK 1.8 in MANIFEST file:

```
Manifest-Version: 1.0
Created-By: 1.8.0_77 (Oracle Corporation)
Main-Class: jep.Run
```

**Comment by bsteffensmeier** [comment]
You must be using the jar from maven central? We use travis to automatically test java 7 compatibility so I am certain it works on a clean build, however I am still trying to work out the kinks in the maven release so I probably messed that up.

I thought I had included "-source 1.7 -target 1.7" in the javac command when I built the maven jar, but I must've had cached class files or messed up the commands. I can generate a new jar using java 7 but I am not sure how to release it to maven central, I would assume I am not allowed to release a new jar with the same version? I am not a maven user, so I am not sure how this type of thing is typically handled on maven projects.

**Comment by nando2301** [comment]
Thanks for answer, I install with `pip install jep` and then copy jar to my Maven Local Repository and add it with `pom.xml` to my project, yesterday I used `python setup.py build install` to get a compiled version, but was the same result, after some tests I detected that you use `def get_java_home():` to set `$JAVA_HOME`, my OSX returns JDK 1.8 with command `/usr/libexec/java_home`, then I fix` _java_home` to `_java_home = "/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home"` to compile, finally it works, but now I have other problems running a script with `openpyxl` (Python Excel Module) and running script with arguments like this:

```python /Users/fernando/Documents/ms/Proyectos/Aeromexico/python-scripts/polizas_por_tipo.py --in /Users/fernando/Documents/ms/Proyectos/Aeromexico/python-scripts/source/AME880912I89201706PL-281217.xml --out /Users/fernando/ownCloud/AeromexicoTemp/AME880912I89201706PL-281217.xlsx --log DEBUG```

**Comment by bsteffensmeier** [comment]
I tried to release a new 3.7.1 compiled with java 7 to maven central and I get the following error:

`Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/black/ninia/jep/3.7.1/jep-3.7.1.jar'`

Since I cannot update existing artifacts, I don't think there is anything I can do to fix the current 3.7.1 jars on maven central. I think I might be able to get around it by adding a build number or qualifier, something like `jep-3.7.1-1` or `jep-3.7.1-2` or maybe even `jep-3.7.1-java7`. I'm not 100% sure that would work or which option is best, so I am going to wait and see if anyone with more maven experience will comment on this issue with a recommendation.

**Comment by nando2301** [comment]
I did not find the repository in maven, there are other jars https://mvnrepository.com/search?q=jep but not this. I'm not a experienced developer and I only use maven to fast integrate libraries to my projects. We will wait comments about it.
Thanks @bsteffensmeier

**Comment by bsteffensmeier** [comment]
I had incorrectly assumed you got jars off maven central and they were incorrect. I just now downloaded the jars from http://repo1.maven.org/maven2/black/ninia/jep/3.7.1/ and checked the classfile version and it is 51 which is java 1.7, so I guess there really isn't a problem with classfile versioning, I was just looking in the wrong spot.

**Comment by nando2301** [comment]
Oh, Thanks for clarify, I was looking for it in another repository

**Comment by bsteffensmeier** [comment]
Closing this as it is inactive and appears to be a problem with the environment, not with the jep project.
