### ISSUE TITLE
initialization of ujson raised unreported exception

### ISSUE THREAD

**Issue by bennylut** [ninia/jep#107]
Hello, I am trying to load ujson (actually, a module that uses it) and receiving the following error
```
Exception in thread "main" jep.JepException: <class 'SystemError'>: initialization of ujson raised unreported exception
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:609)
```

The minimal code that reproduces this problem is: 
```java
    Jep jep = new Jep(false);
    jep.eval("import ujson");
```

Is there anything that I am doing wrong?

- OS Platform, Distribution, and Version: 
Linux - 64bit, mint 18

- Python Distribution and Version:
CPython 3.6.3 

- Java Distribution and Version:
Oracle JVM 1.8.0-151

**Comment by bsteffensmeier** [comment]
I installed ujson on one of my test machines and wrote a java main with the code you included and I do not receive any errors. There seems to be more than one json parsing library called ujson, can you confirm that you are using using Ultrajson 1.35, which is the one in pypi? Also are you using jep 3.7.1?

Also could you try running the jep command that is installed in the python bin directory and see if it is possible to import ujson from the interpreter.

**Comment by bsteffensmeier** [comment]
Closing due to inactivity. There is not enough information for me to identify the problem, this can be reopened if anyone can provide additional details.
