### ISSUE TITLE
"import tensorflow" causes undefined symbol: PyExc_NotImplementedError

### ISSUE THREAD

**Issue by strelec** [ninia/jep#128]
jep.eval("import tensorflow") causes an exception with Jep, but works with python REPL.

---

[error] Exception in thread "main" jep.JepException: <class 'ImportError'>: Traceback (most recent call last):
[error]   File "/home/rok/.local/lib64/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
[error]     from tensorflow.python.pywrap_tensorflow_internal import *
[error]   File "/home/rok/.local/lib64/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
[error]     _pywrap_tensorflow_internal = swig_import_helper()
[error]   File "/home/rok/.local/lib64/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
[error]     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
[error]   File "/usr/lib64/python3.5/imp.py", line 243, in load_module
[error]     return load_dynamic(name, filename, file)
[error]   File "/usr/lib64/python3.5/imp.py", line 343, in load_dynamic
[error]     return _load(spec)
[error] ImportError: /home/rok/.local/lib64/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: PyExc_NotImplementedError
[error] 
[error] 
[error] Failed to load the native TensorFlow runtime.
[error] 
[error] See https://www.tensorflow.org/install/install_sources#common_installation_problems
[error] 
[error] for some common reasons and solutions.  Include the entire stack trace
[error] above this error message when asking for help.
[error] 	at /home/rok/.local/lib64/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.<module>(pywrap_tensorflow.py:74)
[error] 	at /home/rok/.local/lib64/python3.5/site-packages/tensorflow/python/__init__.<module>(__init__.py:49)
[error] 	at /home/rok/.local/lib64/python3.5/site-packages/tensorflow/__init__.<module>(__init__.py:24)
[error] 	at <string>.<module>(<string>:1)
[error] 	at jep.Jep.eval(Native Method)
[error] 	at jep.Jep.eval(Jep.java:609)

- OS Platform, Distribution, and Version:
Gentoo Linux
Tensorflow 1.7

- Python Distribution and Version:
3.5

- Java Distribution and Version:
Java 8

**Comment by strelec** [comment]
Solved it with LD_PRELOAD env variable.
