### ISSUE TITLE
Pyspark session creation fails from interactive jep session

### ISSUE THREAD

**Issue by SemanticBeeng** [ninia/jep#132]
- OS Platform, Distribution, and Version: Ubuntu 16
- Python Distribution and Version: 3.6.4
- Java Distribution and Version:  "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

```
from pyspark.sql import SparkSession
from pyspark import SparkContext
from pandas import *

sparkMaster = "spark://spark-master:7077"
hiveMetastore = "thrift://hive-metastore:9083"
appName = "jeptest"

spark = SparkSession.builder.master(sparkMaster).appName(appName) \
   .config("hive.metastore.uris", hiveMetastore) \
   .config("spark.sql.execution.arrow.enabled", "true") \
   .config("spark.sql.shuffle.partitions", "10").getOrCreate()
```

Works from a python session and prints
```
^MWarning: Ignoring non-spark config property: hive.metastore.uris=thrift://hive-metastore:9083
2018-05-01 10:09:38 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
```

But fails from a `jep` interactive session
```
Warning: Ignoring non-spark config property: hive.metastore.uris=thrift://hive-metastore:9083
2018-05-01 10:13:48 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
jep.JepException: <class 'ValueError'>: signal only works in main thread
	at /development/bin/python/conda3/envs/dev-ds/lib/python3.6/signal.signal(signal.py:47)
	at /development/bin/python/conda3/envs/dev-ds/lib/python3.6/site-packages/pyspark/context._do_init(context.py:238)
	at /development/bin/python/conda3/envs/dev-ds/lib/python3.6/site-packages/pyspark/context.__init__(context.py:118)
	at /development/bin/python/conda3/envs/dev-ds/lib/python3.6/site-packages/pyspark/context.getOrCreate(context.py:331)
	at /development/bin/python/conda3/envs/dev-ds/lib/python3.6/site-packages/pyspark/sql/session.getOrCreate(session.py:173)
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:609)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:609)
	at jep.Run.run(Run.java:73)
	at jep.Run.main(Run.java:151)
```

Same with `spark = SparkSession.builder.master(sparkMaster).appName(appName).getOrCreate()`.

Why would this check fail in `jep`?

https://github.com/apache/spark/blob/6782359a04356e4cde32940861bf2410ef37f445/python/pyspark/context.py#L237

Curiously if I do this in `jep` session right after I get "True"

```
>>> isinstance(threading.current_thread(), threading._MainThread)
True
```

Can see logging on `spark` : it can reach it and start application but it is killed right away.

Used `conda` env

```

conda install -c conda-forge numpy=1.14.2 -y
conda install -c conda-forge pandas=0.22.0 -y
conda install -c conda-forge cython=0.28.1 -y
conda install -c conda-forge boost-cpp=1.66.0 -y
conda install -c conda-forge parquet-cpp=1.4.0 -y
conda install -c conda-forge pyarrow=0.9.0 -y
conda install -c conda-forge pyspark=2.3.0 -y

conda install -c hcc tensorflow=1.7.0 -y
 
conda install -c conda-forge r-base=3.4.3 -y
conda install -c conda-forge r-magrittr=1.5 -y
```

**Comment by ndjensen** [comment]
> UPDATE: Same code works from a programmatic jep session (using pyspark as shared module - do not know if relevant)

To clarify, it doesn't work when you're using the Jep command line interpreter/console but does work when you're running a Java program?

**Comment by SemanticBeeng** [comment]
Yes

**Comment by bsteffensmeier** [comment]
You cannot initialize pyspark on a sub interpreter because it tries to install a signal which isn't working. Using shared modules initializes pyspark on the main thread so the signal installation works. Similar to other python projects that don't work in sub-interpreters pyspark has to be a shared module so I think we can close this.
