### ISSUE TITLE
jep.JepException: <class 'ImportError'>: ctypes.c_longlong 

### ISSUE THREAD

**Issue by moksie** [ninia/jep#134]
- OS Platform, Distribution, and Version: Windows 10
- Python Distribution and Version: 3.5
- Java Distribution and Version: jdk1.8.0_92

Currently I am working on a Java project that needs to consult with scipy module for evaluating numerical operations. But I got this exception when I try to invoke some functions from that module. Consider the following code snippet,

```Java 
Jep jep = new Jep();
jep.eval("from scipy import integrate as integrate");
Object value = jep.getValue("integrate.quad(lambda x: 2*x, 2, 4)");
System.out.println(value);
```

It results in the following exception
```Java
Exception in thread "main" jep.JepException: <class 'ImportError'>: ctypes.c_longlong
	at C:\Python\Python35\lib\site-packages\jep\java_import_hook.__getattr__(java_import_hook.py:32)
	at C:\Python\Python35\lib\site-packages\numpy\core\_internal._getintp_ctype(_internal.py:230)
	at C:\Python\Python35\lib\site-packages\numpy\ctypeslib.<module>(ctypeslib.py:86)
	at C:\Python\Python35\lib\site-packages\numpy\__init__.<module>(__init__.py:167)
	at C:\Users\Maks\AppData\Roaming\Python\Python35\site-packages\scipy\__init__.<module>(__init__.py:62)
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:609)
	at formula.parser.Interpreter.main(Interpreter.java:1541)
Caused by: java.lang.ClassNotFoundException: ctypes.c_longlong
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Process finished with exit code 1
```

**Comment by moksie** [comment]
Thanks for pointing that out. Yes, jython and JyNI were the culprit here. When I removed those from the classpath it worked like a charm.
