### ISSUE TITLE
Numpy imports on command line but not when called from Java

### ISSUE THREAD

**Issue by reid-fu** [ninia/jep#143]
- OS Platform, Distribution, and Version: Ubuntu 16.04.3
- Python Distribution and Version: 2.7.12
- Java Distribution and Version: OpenJDK Java 8

When I run "jep" or "python" from the command line and execute "import numpy", it gives no error messages. I have a Java file in Eclipse that calls a Python script that uses numpy. When I run it, it gives the following error message:

```
Exception in thread "main" jep.JepException: <type 'exceptions.ImportError'>: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /home/reid/.local/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyExc_UserWarning
	at /home/reid/.local/lib/python2.7/site-packages/numpy/core/__init__.<module>(__init__.py:26)
	at /home/reid/.local/lib/python2.7/site-packages/numpy/lib/type_check.<module>(type_check.py:11)
	at /home/reid/.local/lib/python2.7/site-packages/numpy/lib/__init__.<module>(__init__.py:8)
	at /home/reid/.local/lib/python2.7/site-packages/numpy/add_newdocs.<module>(add_newdocs.py:13)
	at /home/reid/.local/lib/python2.7/site-packages/numpy/__init__.<module>(__init__.py:142)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:609)
	at java_python_tutorial.MainJEP.main(MainJEP.java:10)
```
For reference, this is the Java file:
```
package java_python_tutorial;
import jep.Jep;
import jep.JepException;

public class MainJEP {
	public static void main(String[] args) throws JepException {
		Jep jep = new Jep(false);
		jep.eval("import sys");
		jep.eval("print(sys.version)");
		jep.eval("import numpy");
		jep.close();
	}
}
```

**Comment by ndjensen** [comment]
That error message:

> 
> Exception in thread "main" jep.JepException: <type 'exceptions.ImportError'>: 
> Importing the multiarray numpy extension module failed.  Most
> likely you are trying to import a failed build of numpy.
> If you're working with a numpy git repo, try `git clean -xdf` (removes all
> files not under version control).  Otherwise reinstall numpy.

is coming out of numpy.  Do you have more than one Python install on your system and therefore potentially more than one numpy?  It's possible that when you are running Jep from the command line it's using one set of Python (and numpy) libraries while running Jep from your Java application is using a different Python and its numpy libraries.  Open up the jep script in a text editor and see if you can spot what it is doing differently (especially regarding environment variables) than your Java application.

**Comment by bsteffensmeier** [comment]
An undefined python symbol usually indicates that you need to set LD_PRELOAD because the numpy shared library is not properly declaring its dependencies, this is discussed on the [wiki](https://github.com/ninia/jep/wiki/Linux#ld_preload).

**Comment by ndjensen** [comment]
Closing due to lack of activity.

**Comment by NathanielRN** [comment]
I had almost exactly the same issue trying to import `PyExc_NameError`. I had to provide the `libpython3.8.so` file to JEP and everything worked finally:

```
LIBPY=<path of python I want jep to use>

export PYTHONHOME="$LIBPY/python3.8/"

export LD_PRELOAD="$LD_PRELOAD:$LIBPY/python3.8/lib/libpython3.8.so"
```
