### ISSUE TITLE
Running Ray with Jep

### ISSUE THREAD

**Issue by aitorhh** [ninia/jep#164]
- OS Platform, Distribution, and Version: Ubuntu 16.04.5 LTS
- Python Distribution and Version: Python 3.6.5 (pyenv)
- Java Distribution and Version: Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
- Jep Version: jep==3.8.2
- Python packages used (e.g. numpy, pandas, tensorflow): ray (https://ray.readthedocs.io/en/latest/index.html)

I did a quick test to try to run Ray (Ray is a flexible, high-performance distributed execution framework.) inside Jep. After compiling the python library, I want run a simple test 

    import ray
    ray.init(redis_addres="xxxx")

I got the following error:

> 21:30:36.545 [pool-1-thread-1-ScalaTest-running-JepSimpleSpec] ERROR test.processors.ProcessorHelpers$ - {}
... removed error with 'argv' with has a simple solution. The remaining part is valid ...
> Fatal Python error: Py_EndInterpreter: not the last thread
> 
> Thread 0x00007f659bfff700 (most recent call first):
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/_compat.py", line 79 in recv
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/connection.py", line 174 in _read_from_socket
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/connection.py", line 216 in readline
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/connection.py", line 284 in read_response
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/connection.py", line 624 in read_response
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/client.py", line 2408 in _execute
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/client.py", line 2430 in parse_response
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/client.py", line 2501 in listen
>   File "/home/aitorhh/workspace/ray/python/ray/worker.py", line 2027 in print_error_messages
>   File "/home/aitorhh/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 864 in run
>   File "/home/aitorhh/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916 in _bootstrap_inner
>   File "/home/aitorhh/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 884 in _bootstrap
> 
> Thread 0x00007f65997fe700 (most recent call first):
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/_compat.py", line 79 in recv
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/connection.py", line 174 in _read_from_socket
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/connection.py", line 216 in readline
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/connection.py", line 284 in read_response
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/connection.py", line 624 in read_response
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/client.py", line 2408 in _execute
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/client.py", line 2430 in parse_response
>   File "/home/aitorhh/.virtualenvs/test-jep/lib/python3.6/site-packages/redis/client.py", line 2501 in listen
>   File "/home/aitorhh/workspace/ray/python/ray/import_thread.py", line 60 in _run
>   File "/home/aitorhh/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 864 in run
>   File "/home/aitorhh/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916 in _bootstrap_inner
>   File "/home/aitorhh/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 884 in _bootstrap
> 
> Current thread 0x00007f65f524c700 (most recent call first):
> Exception in thread "Thread-21" java.io.EOFException
>         at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2917)
>         at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1502)
>         at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
>         at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:809)
>         at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:798)
> 
> 

I understand the error with `argv` and I can easily get rid of that. But I guess the problem is the multi-threading solution of the library itself.

If, I'm correct, it was stated somewhere in the Wiki, the Jep's limitation with multi threading (I cannot find after a quick look)

Any suggestion??

**Comment by ndjensen** [comment]
Did you close the Jep instance and at the time of close() that's when the error comes?  Take a look at this issue https://github.com/ninia/jep/issues/161 and the related mailing list post mentioned in there.

Jep requires that the Java thread that created the Jep instance be the only Java thread that calls into that Jep instance.  Here's the wiki, though it's pretty short: https://github.com/ninia/jep/wiki/How-Jep-Works#threading-complications

Regarding Python threads spawned from a Jep instance, the current theory goes that if you manage them yourself you might be able to get it to work.  I haven't tried it and we haven't received feedback on how well that works or not.

**Comment by bsteffensmeier** [comment]
CLosing due to inactivity.
