### ISSUE TITLE
jep.JepException: <type 'exceptions.ImportError'>: No module named python.framework

### ISSUE THREAD

**Issue by xvolks** [ninia/jep#173]
- OS Platform, Distribution, and Version:
macOS 10.14.1
- Python Distribution and Version:
macOS's 2.7.10
- Java Distribution and Version:
Oracle 1.8.0_172
- Jep Version:
3.8.2 installed with brew
- Python packages used (e.g. numpy, pandas, tensorflow):
keras and tensorflow.

When I run a simple python script it seems to work great but if I try to import Keras, it throws an exception:
jep.JepException: <type 'exceptions.ImportError'>: No module named python.framework

I've tried to install jep on 3 different macs with the same result.

I was also unable to install JEP with Python 3.7.1 with following error `TypeError: '_NamespacePath' object does not support indexing`

I've joined a Kotlin source code demonstrating this behaviour.
Its output is :
```
Hello, World from kotlin
Hello world from python
2.7.10 (default, Aug 17 2018, 17:41:52) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
Using TensorFlow backend.
Exception in thread "main" jep.JepException: <type 'exceptions.ImportError'>: No module named python.framework
	at /Users/xvolks/transfer_learning/lib/python2.7/site-packages/keras/backend/tensorflow_backend.<module>(tensorflow_backend.py:6)
	at /Users/xvolks/transfer_learning/lib/python2.7/site-packages/keras/backend/__init__.<module>(__init__.py:89)
	at /Users/xvolks/transfer_learning/lib/python2.7/site-packages/keras/utils/conv_utils.<module>(conv_utils.py:9)
	at /Users/xvolks/transfer_learning/lib/python2.7/site-packages/keras/utils/__init__.<module>(__init__.py:6)
	at /Users/xvolks/transfer_learning/lib/python2.7/site-packages/keras/__init__.<module>(__init__.py:3)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:507)
	at org.xvolks.research.Hello$Companion.evalMultiline(Hello.kt:31)
	at org.xvolks.research.Hello$Companion.access$evalMultiline(Hello.kt:26)
	at org.xvolks.research.Hello.eval(Hello.kt:22)
	at org.xvolks.research.HelloKt.main(Hello.kt:10)

```
[Hello.kt.gz](https://github.com/ninia/jep/files/2578450/Hello.kt.gz)

**Comment by xvolks** [comment]
As asked, I have modified the code of Hello.kt this way:
```
package org.xvolks.research

import jep.Jep
import jep.JepConfig
import java.util.*


fun main(args: Array<String>) {
    println("Hello, World from kotlin")
    val hello = Hello()

    hello.eval("""
import sys
print('Hello world from python')
print (sys.version)
import tensorflow
print(tensorflow.__path__)
import tensorflow.python.framework
""")

}
```

The output is 
```
Hello, World from kotlin
Hello world from python
2.7.10 (default, Aug 17 2018, 17:41:52) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
[]
Exception in thread "main" jep.JepException: <type 'exceptions.ImportError'>: No module named python.framework
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:507)
	at org.xvolks.research.Hello$Companion.evalMultiline(Hello.kt:45)
	at org.xvolks.research.Hello$Companion.access$evalMultiline(Hello.kt:40)
	at org.xvolks.research.Hello.eval(Hello.kt:36)
	at org.xvolks.research.HelloKt.main(Hello.kt:22)

```

I wonder why `tensorflow` is not really found, but does not fail on import statement.

**Comment by bsteffensmeier** [comment]
dl4j must be pulling in a Java package named tensorflow. By default Jep scans the classpath and allows you to import all your Java packages into Python, this takes precedence over the Python packages if there is a naming conflict. To resolve this I recommend passing a custom [ClassEnquirer](http://ninia.github.io/jep/javadoc/3.8/jep/ClassEnquirer.html) into you JepConfig. You want to make sure that isJavaPackage() returns false for tensorflow. You should be able to simply extend the default ClassList and overriding that one method to check for tensorflow.
