### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native Library libjep.so already loaded in another classloader

### ISSUE THREAD

**Issue by zoltansx** [ninia/jep#214]
Dear All,

I use JEP in a J2EE container (WildFly), as part of a WAR file.
The code using JEP, will fail with the following message, it the WAR file has been redeployed in the running WildFly instance, i.e. it looks like to previously loaded JEP env is not correctly undeployed. 
Is there anything I'm missing?

```
Caused by: java.lang.UnsatisfiedLinkError: Native Library /home/zoltansx/.local/lib/python3.6/site-packages/jep/libjep.so already loaded in another classloader
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at jep.LibraryLocator.searchPackageDir(LibraryLocator.java:213)
        at jep.LibraryLocator.searchUserSitePackages(LibraryLocator.java:188)
        at jep.LibraryLocator.findJepLibrary(LibraryLocator.java:278)
        at jep.MainInterpreter.initialize(MainInterpreter.java:130)
        at jep.MainInterpreter.getMainInterpreter(MainInterpreter.java:101)
        at jep.Jep.<init>(Jep.java:256)
```

I always initialize JEP the following way:

```
try (SharedInterpreter jep = new SharedInterpreter()) {
...
}
```

**Environment:**
- Ubuntu 18.04.3 LTS
- Python 3.6.8 ( installed with `sudo apt-get install python3`)
- OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
- jep-3.9.0. ( installed with `pip3 install jep`)
- Python packages used (numpy, scipy):

**Comment by Cocoa-Puffs** [comment]
The problem comes from trying to import an already loaded shared library. One way to solve this would be to free the shared library during undeployment by copying the shared library to a temporary file that gets deleted during undeployment. Also checking whether the shared library is already in the classpath during initialization. This snippet would also solve an error where a new Stateless EJB during it's initialization phase would try to import the shared library again.

```java
Field loadedLibraryNames = ClassLoader.class.getDeclaredField("loadedLibraryNames");
loadedLibraryNames.setAccessible(true);
Set<String> libs = (Set<String>) loadedLibraryNames.get(this.getClass().getClassLoader());

if (!libs.contains(libName)) {
   URL url = this.getClass().getResource("/" + libName);
   File tmpDir = Files.createTempDirectory("my-native-lib").toFile();
   tmpDir.deleteOnExit();
   File nativeLibTmpFile = new File(tmpDir, libName);
   nativeLibTmpFile.deleteOnExit();
   try (InputStream in = url.openStream()) {
      Files.copy(in, nativeLibTmpFile.toPath());
   }
   System.load(nativeLibTmpFile.getAbsolutePath());
}
```

**Comment by zoltansx** [comment]
We ended up deploying jep-3.9.0.jar directly to wildfly and I think that served the purpose well, so let's close the case.
