### ISSUE TITLE
How can I get spaCy to work in java with jep?

### ISSUE THREAD

**Issue by Boreaso** [ninia/jep#216]
**Describe the problem**
I want to use spaCy in my project, but I got a fatal error when load spaCy model: 
``` Java
    public static void main(String[] args) throws JepException {
        try (Interpreter interp = new SharedInterpreter()) {
            interp.exec("import spacy");
            interp.set("model", "en_core_web_sm");
            interp.exec("spacy.load(model)");
        }
    }
```
I got the following errors:

``` Text
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f05d435d703, pid=60792, tid=0x00007f064d39b700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_221-b11) (build 1.8.0_221-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.221-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libstdc++.so.6+0xd5703]  std::string::swap(std::string&)+0x3
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /usr1/panlongfei/projects/JepTest/hs_err_pid60792.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```
How can I fix this? Help.

**Comment by bsteffensmeier** [comment]
Can you attach the hs_err_pid file?

**Comment by Boreaso** [comment]
@bsteffensmeier Hello, here is the log file, please check it.
[hs_err_pid86071.log](https://github.com/ninia/jep/files/3877596/hs_err_pid86071.log)

**Comment by bsteffensmeier** [comment]
When I run your example I get the following error:

``` Text
Exception in thread "main" jep.JepException: <class 'AttributeError'>: module 'sys' has no attribute 'argv'
	at /home/ben/.local/lib/python3.6/site-packages/plac_ext.Interpreter(plac_ext.py:1144)
	at /home/ben/.local/lib/python3.6/site-packages/plac_ext.<module>(plac_ext.py:879)
	at /home/ben/.local/lib/python3.6/site-packages/plac.<module>(plac.py:29)
	at /home/ben/.local/lib/python3.6/site-packages/spacy/cli/download.<module>(download.py:4)
	at /home/ben/.local/lib/python3.6/site-packages/spacy/cli/__init__.<module>(__init__.py:1)
	at /home/ben/.local/lib/python3.6/site-packages/spacy/__init__.<module>(__init__.py:13)
	at <string>.<module>(<string>:1)
	at jep.Jep.exec(Native Method)
	at jep.Jep.exec(Jep.java:478)
	at Test.main(Test.java:8)
```
I added a few lines and it completes without errors.

``` java
        try (Interpreter interp = new SharedInterpreter()) {
            interp.exec("import sys");
            interp.exec("sys.argv=[]");
            interp.exec("import spacy");
            interp.set("model", "en_core_web_sm");
            interp.exec("spacy.load(model)");
        }
```

Nothing stands out to me in you hs_err_pid and I cannot repeat your problem so there is not much I can do. I am using spacy version 2.2.3, which version are you using?

**Comment by Boreaso** [comment]
@bsteffensmeier Thanks a lot, bsteffensmeier. I also ran the example successfully in my anaconda virtual environment. I don't know why this happens in my anaconda base  environment. Maybe some package conflicts?

**Comment by Boreaso** [comment]
@bsteffensmeier By the way, do you have java multi-thread example for the usage of SharedInterpreter?

**Comment by bsteffensmeier** [comment]
You cannot use a Jep interpreter in more than one thread, so you must make a new interpreter in each thread for a multithreaded application, Here is a simple example:

```java
public class TestThread extends Thread {

    public void run() {
        try (Interpreter interp = new SharedInterpreter()) {
            interp.set("threadName", Thread.currentThread().getName());
            interp.exec("print(threadName, 'has started.')");
            interp.exec("from random import randint");
            interp.exec("from time import sleep");
            interp.exec("sleep(randint(5,10))");
            interp.exec("print(threadName, 'is done.')");
        } catch (JepException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) throws InterruptedException {
        TestThread[] threads = new Test[5];
        for(int i = 0 ; i < threads.length ; i += 1){
            threads[i] = new TestThread();
            threads[i].start();
        }
        for(int i = 0 ; i < threads.length ; i += 1){
            threads[i].join();
        }
    }
}

```

**Comment by Boreaso** [comment]
@bsteffensmeier Can I use java thread pool to do this operations？Loading spaCy model is really time consuming, I want to do this operation during init stage and reuse this SharedInterpreter in the following steps.

**Comment by ndjensen** [comment]
If you're using SharedInterpreters, then spaCy will only be imported/loaded once into the Python interpreter.  If you want to have a Java thread pool and each thread does its own work, that is fine, just make a separate SharedInterpreter instance for each Java thread.  Please be aware that running multiple threads may not result in improved performance, it is dependent on how spaCy was written.  For more information, see the wiki page about the GIL: https://github.com/ninia/jep/wiki/Jep-and-the-GIL

**Comment by Boreaso** [comment]
@ndjensen Thanks a lot.
