### ISSUE TITLE
Specify which interpreter needs to be loaded

### ISSUE THREAD

**Issue by BrightXiaoHan** [ninia/jep#350]
I want to load a conda env python interpreter like this:
```
this.interp = new SharedInterpreter("/path/to/env/bin/python");
```
How can I do this?

**Comment by ndjensen** [comment]
The recommended way to set which Python to use is through environment variables, specifically on Linux it's LD_LIBRARY_PATH.  If you need to do it programmatically you can try to use PyConfig like

```java
PyConfig pyConfig = new PyConfig();
pyConfig.setPythonHome("/path/to/python/dir");
MainInterpreter.setInitParams(pyConfig);
this.interp = new SharedInterpreter();
```
I don't remember the intricacies of PYTHONHOME and what takes precedence on loading libraries.

If you wanted to have two different interpreters pointed at different Python installs in the same process, that is not possible.

**Comment by BrightXiaoHan** [comment]
Thanks, your solution works for me. But I met another issue.  My python env is a conda env.
```
Exception in thread "main" jep.JepException: <class 'ImportError'>: DLL load failed: 找不到指定的模块。
        at D:\Projects\javatest\pythonenv\lib\sqlite3\dbapi2.<module>(dbapi2.py:27)
        at D:\Projects\javatest\pythonenv\lib\sqlite3\__init__.<module>(__init__.py:23)
        at D:\Projects\javatest\pythonenv\lib\site-packages\nltk\corpus\reader\panlex_lite.<module>(panlex_lite.py:15)
        at D:\Projects\javatest\pythonenv\lib\site-packages\nltk\corpus\reader\__init__.<module>(__init__.py:106)
        at D:\Projects\javatest\pythonenv\lib\site-packages\nltk\corpus\__init__.<module>(__init__.py:64)
        at D:\Projects\javatest\pythonenv\lib\site-packages\nltk\translate\meteor_score.<module>(meteor_score.py:13)
        at D:\Projects\javatest\pythonenv\lib\site-packages\nltk\translate\__init__.<module>(__init__.py:24)
        at D:\Projects\javatest\pythonenv\lib\site-packages\nltk\__init__.<module>(__init__.py:153)
        at D:\Projects\javatest\pythonenv\lib\site-packages\lib_translate-1.0-py3.7.egg\libtranslate\translate\sentence_split.<module>(sentence_split.py:38)
        at D:\Projects\javatest\pythonenv\lib\site-packages\lib_translate-1.0-py3.7.egg\libtranslate\translate\__init__.<module>(__init__.py:5)
        at <string>.<module>(<string>:1)
        at jep.Jep.exec(Native Method)
        at jep.Jep.exec(Jep.java:339)
        at com.lanmt.translate.JTranslator.<init>(JTranslator.java:22)
        at Example.main(Example.java:6)
```
It seems that the interpreter can't load dll library. There is no such issue when I set which Python to use is through environment variables instead of `pyConfig.setPythonHome("/path/to/python/dir");`.
