### ISSUE TITLE
jep.JepException: <class 'SystemError'>: initialization of md__mypyc did not return an extension module

### ISSUE THREAD

**Issue by mwxiaomao** [ninia/jep#542]
**Describe the problem**
A clear and concise description of what the problem is.

**Environment (please complete the following information):**
- OS Platform, Distribution, and Version: 10.12
- Python Distribution and Version: 3.8
- Java Distribution and Version: 1.8
- Jep Version: 4.2.0
- Python packages used (e.g. numpy, pandas, tensorflow): No

jep.JepException: <class 'SystemError'>: initialization of md__mypyc did not return an extension module
	  at /usr/local/python3.8/lib/python3.8/site-packages/charset_normalizer/cd.<module>(cd.py:14) ~[?:?]
	  at /usr/local/python3.8/lib/python3.8/site-packages/charset_normalizer/api.<module>(api.py:5) ~[?:?]
	  at /usr/local/python3.8/lib/python3.8/site-packages/charset_normalizer/__init__.<module>(__init__.py:24) ~[?:?]
	  at /usr/local/python3.8/lib/python3.8/importlib/__init__.import_module(__init__.py:127) ~[?:?]
	  at /usr/local/python3.8/lib/python3.8/site-packages/requests/compat._resolve_char_detection(compat.py:24) ~[?:?]
	  at /usr/local/python3.8/lib/python3.8/site-packages/requests/compat.<module>(compat.py:30) ~[?:?]
	  at /usr/local/python3.8/lib/python3.8/site-packages/requests/exceptions.<module>(exceptions.py:9) ~[?:?]
	  at /usr/local/python3.8/lib/python3.8/site-packages/requests/__init__.<module>(__init__.py:45) ~[?:?]
	  at /opt/my/data/dev/app/runner/f143a00e83c98ada8494ac1be4b61b02/application.<module>(application.py:7) ~[?:?]
	  at <string>.<module>(<string>:1) ~[?:?]
	  at jep.Jep.eval(Native Method) ~[jep-4.2.0.jar!/:?]
	  at jep.Jep.eval(Jep.java:326) ~[jep-4.2.0.jar!/:?]
	  at com.xxx.cloud.soar.common.executor.JepExecutor.exec(JepExecutor.java:63) ~[classes!/:1.0.0-SNAPSHOT]

**Comment by Divine1** [comment]
@mwxiaomao  any idea what was the RCA and fix?

iam able to see the error . please help


```

jep.JepException: <class 'SystemError'>: initialization of md__mypyc did not return an extension module
	at C:\Users\658709\AppData\Local\Programs\Python\Python312\Lib\site-packages\charset_normalizer\cd.<module>(cd.py:14)
	at C:\Users\658709\AppData\Local\Programs\Python\Python312\Lib\site-packages\charset_normalizer\api.<module>(api.py:5)
	at C:\Users\658709\AppData\Local\Programs\Python\Python312\Lib\site-packages\charset_normalizer\__init__.<module>(__init__.py:24)
	at C:\Users\658709\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\__init__.<module>(__init__.py:48)
	at C:\Users\658709\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\core\http.<module>(http.py:1)
	at C:\Users\658709\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\core\download_manager.<module>(download_manager.py:5)
	at C:\Users\658709\AppData\Local\Programs\Python\Python312\Lib\site-packages\webdriver_manager\chrome.<module>(chrome.py:4)
	at C:\...\build\resources\main/executor\mypythonscript.<module>(mypythonscript.py:12)
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:326)
	at ...convert(M.java:16)
	at ...ExceptionTest(MTest.java:44)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:767)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)



```

**Comment by KaranCV** [comment]
We are seeing the same error. Out environment is 
OpenJDK 8
Jep 4.2.2
Python 3.12.10
Windows

In which version is the issue fixed ?
We get Tomcat crash randomly. We are assuming it to be this error, since this error gets printed on logs when the crash does not happen. Attaching the crash thread generated when tomcat crashed. 

[hs_err_pid9320.log](https://github.com/user-attachments/files/25254924/hs_err_pid9320.log)
[hs_err_pid12180.log](https://github.com/user-attachments/files/25254925/hs_err_pid12180.log)

This crash was not occurring when we had JEP 3.9 with Python 3.7
Any help would be highly appreciated.
