### ISSUE TITLE
UnsatisfiedLinkError: I am stomped.

### ISSUE THREAD

**Issue by drseung** [ninia/jep#561]
Hi

I keep encountering a **Java.lang.UnsatisfiedLinkError: C:\***: Can't find dependent libraries**. My application ships with an embedded python for windows environments where python is not normally installed. When I unpack this and try to get a **new SharedInterpreter()** I get Java.lang.UnsatisfiedLinkError. I have confirmed that jep.dll is available.

I have tried this with a minimalist embedded **.zip**  python and complete **python312 build**.
I have set **pythonhome** in **jep.pyCconfig** " C:\vapData\***\.vap\py\vi_venv"
I have set the **jepLibraryPath** "C:\Users\***\.vap\py\vi_venv\Lib\site-packages\jep\jep.dll"

Exception in thread "Thread-154" java.lang.UnsatisfiedLinkError: C:\vapData\***\.vap\py\vi_venv\Lib\site-packages\jep\jep.dll: **Can't find dependent libraries**
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2399)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2030)
	at jep.MainInterpreter.initialize(MainInterpreter.java:126)
	at jep.MainInterpreter.getMainInterpreter(MainInterpreter.java:101)
	at jep.Jep.<init>(Jep.java:133)
	at jep.SharedInterpreter.<init>(SharedInterpreter.java:60)
	at ca.okello.vi.central.OsGovernor.getPyInterpreter(OsGovernor.java:400)
	at ca.okello.vi.ui.onBoarding.OnboardingCTRL$2.run(OnboardingCTRL.java:117)
	at java.base/java.lang.Thread.run(Thread.java:1570)

My configuration is 
-- windows 11, 
-- Python 3.12.6
-- Java 22
-- Jep 4.2.0
-- Python packages pytorch, numpy

Any thoughts?

**Comment by drseung** [comment]
Closing this in favor of [This issue](https://github.com/ninia/jep/issues/517)
